model: local:qwen2.5-coder-7b-instruct-mlx
clients:
  - type: openai-compatible
    name: local
    api_base: http://localhost:1234/v1
    api_key: null
    models:
      - name: qwen2.5-coder-7b-instruct-mlx
        max_input_tokens: 8192
      - name: google/gemma-4-26b-a4b-qat
        max_input_tokens: 8192
      - name: qwen/qwen3.6-27b
        max_input_tokens: 8192
